<a href="https://colab.research.google.com/github/jullyoemmanuel/T-cnicas-de-machine-learning/blob/main/Atividade_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Atividade 08

In [2]:
import numpy as np

##arange

In [3]:
arr1 = np.arange(10)
arr2 = np.arange(10, 20)
arr3 = np.arange(10, 20, 2)
arr4 = np.arange(10, 20, 1.4)

##linspace

In [4]:
arr5 = np.linspace(10, 20, 11)
# 10, 11, ..., 20 (11 elementos)
arr6 = np.linspace(10, 20, 101)
# 10, 10.1, ..., 20 (101 elementos)
arr7 = np.linspace(0, np.pi, 100)
# de 0 até pi, 100 elementos

##matriz

In [7]:
minhaMatriz = np.array([[1,2,3],
[4,5,6]])

In [8]:
minhaMatriz = np.array([[1,2,3], [4,5,6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
minhaLista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

In [10]:
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

###matriz de zeros

In [11]:
x = np.zeros(3)
x

array([0., 0., 0.])

In [12]:
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
print(np.zeros(3))

[0. 0. 0.]


In [14]:
print(np.zeros((3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


###matriz de 1

In [15]:
x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [17]:
x = np.ones((5,3))*8
x

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

###matriz diagonal principal

In [18]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

###matriz identidade

In [19]:
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
y = np.eye(5, dtype= int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

###formato da matriz

In [21]:
np.shape(minhaMatriz)

(3, 3)

In [22]:
minhaMatriz.shape

(3, 3)

###tipo da matriz

In [23]:
type(minhaMatriz)

numpy.matrix

In [24]:
minhaMatriz.dtype

dtype('int64')

###selação

In [28]:
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [25]:
minhaMatriz[2, 1]

48

In [26]:
print(minhaMatriz[0,:])

[[13 81 22]]


In [27]:
print(minhaMatriz[:,2])

[[22]
 [59]
 [94]]


In [29]:
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

###operações básicas

In [32]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.sum(arr1) #soma dos valores do array

45

In [34]:
np.prod(arr1) #produto dos valores do array

0

In [35]:
np.cumsum(arr1) #soma aculada

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [36]:
arr1.min() #obtendo o valor mínimo do array

0

In [37]:
arr1.max() #obtendo o valor máximo do array

9

In [38]:
np.mean(arr1) #média dos valores do array

4.5

In [39]:
np.median(arr1) #mediana dos valores do array

4.5

In [41]:
np.var(arr1) #variância do array

8.25

In [42]:
np.std(arr1) #desvio padrão

2.8722813232690143

##Desafio
Criar um array unidimensional usando arange com 20 elementos;
* “Varrer” o array para obter os pares;
* “Varrer” o array para obter os ímpares;
* Obter a média, a soma, o produto, a variância e o desvio padrão
do array.
* Saber se os valores são maiores que 5;
* Obter os valores maiores que 5.

In [44]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
impar = []
par = []

for i in array:
  if (i % 2) == 0:
    par.append(i)
  else:
    impar.append(i)

print('Impares: ', impar)
print('Pares: ', par)

Impares:  [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
Pares:  [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [47]:
print('Média: ',array.mean())

Média:  9.5


In [52]:
print('Produto: ',array.prod())

Produto:  0


In [49]:
print('Variância: ',np.var(array))

Variância:  33.25


In [51]:
print('Desvio padrão: ',np.std(array))

Desvio padrão:  5.766281297335398


In [55]:
v = []
for i in array:
  a = i > 5
  v.append(a)
v

[False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [57]:
v = []
for i in array: 
  if i > 5: v.append(i)
v

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]