<a href="https://colab.research.google.com/github/jullyoemmanuel/T-cnicas-de-machine-learning/blob/main/Aula_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<font color = orange>Aula 06<font/>

##Numpy

In [2]:
import numpy as np # importando biblioteca de algebra linear

In [3]:
minhaLista = [0,1,2,3,4,5,6,7,8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [8]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [11]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
array3 = np.arange(0,10,0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [15]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [16]:
array3 = np.arange(0,10,0.5,dtype = int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
array4 = np.arange(12)

In [18]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [19]:
type(array4)

numpy.ndarray

In [20]:
array4.dtype

dtype('float64')

In [21]:
vetor1 = np.array([0,1,2,3,4])
print(vetor1)

[0 1 2 3 4]


In [22]:
vetor1[3]

3

In [24]:
vetor1[0:2]

array([0, 1])

In [25]:
print(vetor1[0:2])

[0 1]


In [26]:
s = np.array(['Python','Profissional','Java','Água'])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [27]:
s = np.array(['Python',1343143232,'Profissional','Java','Água'])
s

array(['Python', '1343143232', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

In [28]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])